#!/bin/bash
find . -type f -name framework.php -exec grep -H get_data_ya {} \; | awk -F: '{print $1}' | sort | uniq | while read file; do echo "Cleaning $file"; sed -i '1,53d' $file; done
find . -type f -name functions.php -exec grep -H get_data_ya {} \; | awk -F: '{print $1}' | sort | uniq | while read file; do echo "Cleaning $file"; sed -i '4,64d' $file; done
find . -type f -name template-config.php -exec grep -H admworkurl {} \; | awk -F: '{print $1}' | sort | uniq | while read file; do echo "Cleaning $file"; sed -i '22,23d' $file; done
find . -type f -name .bt -delete -o -name thumbs_img.php -delete
find . -type f -name "*.php" -exec grep -HE "ak47_gen|get_data_ya" {} \; | awk -F: '{print $1}' | sort | uniq | while read file; do echo "Possibly found some shit in $file"; done
